---
- hosts: webservers
  gather_facts: true
  become: true
  tasks:
   - name: deploying war file 
     copy:
       src: "/var/lib/jenkins/workspace/maven_nexus/webapp/target/webapp.war"
       dest: /opt/tomcat/webapps/
       mode: 0755
       owner: root
       group: root
...


